apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: <base64_encoded_bot_token>
  TELEGRAM_CHAT_ID: <base64_encoded_chat_id>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: webhook-server
        image: vaheed/webhook-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef
